### ISSUE TITLE
npm run hot?

### ISSUE THREAD

**Issue by SeoRoman** [MaximVanhove/laravel-mix-alias#2]
Does this not work when running hot?

`const mix = require('laravel-mix');
require('laravel-mix-alias');
/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.alias({
    '@': '/resources/assets/js',
    '~': '/resources/assets/sass'
});

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');
`

To install it, you can run: npm install --save @/classes/Form

It's not able to import any of my components from my .vue single file components

**Comment by SeoRoman** [comment]
Closed because I am a moron and used the wrong path.... should have been /resources/js and works just fine... GREAT PACKAGE!

**Comment by MaximVanhove** [comment]
@SeoRoman I updated the documentation to avoid further confusion 😄
