### ISSUE TITLE
path resolve was not working

### ISSUE THREAD

**Issue by darklord1807** [MaximVanhove/laravel-mix-alias#4]
Path resolve was not working with Mix 6. 

Had to update it as follows: 

const mix = require('laravel-mix');
const path2 = require('path');

class Alias {
    register(alias, path = null) {
        const aliases = getAliasesObject(alias, path);

        this.aliases = Object.assign(aliases, this.aliases || {});
        this.rootPath = path2.resolve(__dirname, '../../');

    }

**Comment by MaximVanhove** [comment]
Laravel Mix 6 added this package to the core. You can remove this package from your dependencies 😊

**Comment by pxlrbt** [comment]
@MaximVanhove Thanks for your work on the package. Maybe you want to add a note to the readme, that it's not needed anymore with Laravel Mix 6?
