### ISSUE TITLE
not compatible with laravel-mix 6

### ISSUE THREAD

**Issue by jcarlosraid** [MaximVanhove/laravel-mix-alias#5]
hello this message in laravel-mix 6:
 TypeError: Cannot read property 'resolve' of undefined
    at Alias.register (/home/carlos/Proyectos/kalachakife/node_modules/laravel-mix-alias/index.js:8:37)

**Comment by MaximVanhove** [comment]
Laravel Mix 6 added this package to the core. You can remove this package from your dependencies 😊
